
name: Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 1 * * *'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - mattpolzin2/idris-docker:0.5.1
          - mattpolzin2/idris-docker:0.6.0
          - mattpolzin2/idris-docker:0.7.0
          - mattpolzin2/idris-docker:nightly
    container: ${{ matrix.image }}
    steps:
      - name: Install Dependencies
        run: apt-get update && apt-get -y install git
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
#      - name: Test
#        run: make test
